[tool.poetry]
name = "vulnerability_identification"
version = "0.1.0"
description = ""
authors = [
    "Adam Pogwizd <adam.pogwizd@kandi.io>",
    "Andrew Carlisle <andrew.carlisle@kandji.io>",
    "Nathan Vangheem <nathan.vangheem@kandji.io>",
    "Nikita Samarin <nikita.samarin@kandji.io>",
    "Patrick Bagot <patrick.bagot@kandji.io>"
]

[tool.poetry.dependencies]
python = "3.9.9"
grpcio-tools = "1.41.1"
kandji-tools = {path = "vendor/kandji_tools-3.0.0-py3-none-any.whl"}
isort = "5.10.1"
black = "22.1.0"
flake8 = "4.0.1"
pre-commit = "^2.19.0"
redis = "4.1.1"
SQLAlchemy = "1.4.36"
alembic = "1.7.7"
psycopg2 = "2.9.3"
pydantic = "1.9.1"
requests = "2.26.0"
python-Levenshtein = "0.12.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
